### ISSUE TITLE
Compiler error: 'MessageHandler' is imported from both

### ISSUE THREAD

**Issue by fengyuxx** [mwaylabs/flutter-apns#1]
Flutter 1.6.7 • channel dev • https://github.com/flutter/flutter.git
Framework • revision cba41ca2ec (6 weeks ago) • 2019-05-30 12:04:01 -0700
Engine • revision 58eff77ef2
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 fee615c5a5)

Compiler message:
file:///Users/elvin/.pub-cache/hosted/pub.flutter-io.cn/flutter_apns-1.0.0/lib/apns_connector.dart:5:1: Error: 'MessageHandler' is imported from both 'package:flutter_apns/connector.dart' and 'package:flutter/src/services/binary_messenger.dart'.
import 'package:flutter/services.dart';

**Comment by szotp** [comment]
#2 merged
