### ISSUE TITLE
connector.token listener not called

### ISSUE THREAD

**Issue by Alqueraf** [mwaylabs/flutter-apns#10]
Hey, I'm not getting any value back on the connector.token listener.
Currently on version 1.0.4 of the library and iOS 13.1.2 (physical device).
I've tried with the example app as well and I'm never getting a token back.

**Comment by Alqueraf** [comment]
Not related to this library.
In case it helps anyone, make sure you add "Background Modes" in capabilities and enable "Background fetch" and "Remote notifications"

**Comment by MohammedYAmmar** [comment]
I have the same problem I've Enabled background mode 
but token still return null

**Comment by faldunate** [comment]
Same problem here, I've enabled all, someone has a solution?

**Comment by aatmmr** [comment]
I stumbled upon the same issue (`v1.0.5`). The *Allow Push Messages* permission request was shown on iOS (device and simulator) and, after giving permission, the device token was still null. After double-checking I figured that I missed to enable Push Notifications separately using Xcode (opening `ios\Runner.xcworkspace` with Xcode).

**Comment by szotp** [comment]
I will add log message when token registration fails so error is more obvious. Note tokens never work on the simulator, you need to run on device.

**Comment by Yirmerah** [comment]
I have the same issue, ive enable all (enable Push Notifications and Background Modes, and enable Background fetch and Remote notifications under Background Modes.)

**Comment by jeffsorr** [comment]
Probably unrelated, I was getting a null token because in my `AppDelegate.swift` I had added an override func for `didRegisterForRemoteNotificationsWithDeviceToken` which was overriding the plugin's implementation
