### ISSUE TITLE
firebase_messaging update to version 13.0.2

### ISSUE THREAD

**Issue by fernandomiyahiradb1** [mwaylabs/flutter-apns#101]
Please, update firebase_messaging to version 13.0.2

Has an important correction to flutter 3.3.0:
https://github.com/firebase/flutterfire/issues/9446

DOCS: update docs to use @pragma('vm:entry-point') annotation for messaging background handler ([#9494](https://github.com/firebase/flutterfire/issues/9494)). ([27a7f44e](https://github.com/firebase/flutterfire/commit/27a7f44e02f2ed533e0249622afdd0a421261385))

**Comment by FabioPaganoAPSystem** [comment]
I would like to know if it is still mandatory to put the pragma annotation for messaging background handler or using this version it is no more needed. Thank you.

**Comment by fernandomiyahiradb1** [comment]
> I would like to know if it is still mandatory to put the pragma annotation for messaging background handler or using this version it is no more needed. Thank you.

Yeahp just add pragma annotation and messaging background working perfectly. The upgrade is not needed for this case.
