### ISSUE TITLE
Cannot get any iOS app to work

### ISSUE THREAD

**Issue by rufw91** [mwaylabs/flutter-apns#13]
Hi so i saw this plugin a few days ago and decided to test it for iOS. The following is an overview of my project:

1. I used the example project in the repo and changed the pubspec.yaml to use dependency: flutter_apns: ^1.0.5
2. I changed the bundle id, and team id using xcode to my values, 
3. I enabled push notifications, background fetch and remote notifications in xcode
4. I created the online configuration by creating certificates for push then downloaded and generated p12
5. On running the app, the token is never generated (print('Token ${connector.token.value}');) is never called

What im i doing wrong. Help. 
Thanks in advance.

EDIT:
I get this error in XCode 
"invalid capability (0x14) "Unable to insert COPY_SEND""

**Comment by aatmmr** [comment]
Hej @rufw91! 

How do you initialise the connector and retrieve the token?

**Comment by rufw91** [comment]
I followed the sample as is so that would be the call to createPushConnetor()

**Comment by aatmmr** [comment]
Here is how I initialise the push connector. It is wrapped in a `init()` as you can see below. Have you add the respective listeners before you call `connector.requestNotificationPermissions()`?

```dart
/// Initialise push messaging for device.
init() {
  connector.configure(
    onLaunch: _onLaunch,
    onResume: _onResume,
    onMessage: _onMessage,
  );

  connector.token.addListener(() {
    logger.log('$runtimeType / init / Provider: ${connector.providerType}');
    logger.log('$runtimeType / init / Token: ${connector.token.value}');
    deviceToken = connector.token.value;
    notifyListeners();
  });

  connector.isDisabledByUser.addListener(() {
    logger.log('$runtimeType / init / Push was disabled by user.');
  });

  connector.requestNotificationPermissions();
}
```

**Comment by rufw91** [comment]
I didnt use init will test in a few and get back.

**Comment by rufw91** [comment]
Ok here is the code im using is:

`import 'package:flutter_apns/apns.dart';
import 'package:flutter/material.dart';
import 'dart:developer' as logger;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final connector = createPushConnector();

  /// Initialise push messaging for device.
  init() {
    connector.configure(
      onLaunch: onPush,
      onResume: onPush,
      onMessage: onPush,
    );

    connector.token.addListener(() {
      logger.log('$runtimeType / init / Provider: ${connector.providerType}');
      logger.log('$runtimeType / init / Token: ${connector.token.value}');
    });

    connector.isDisabledByUser.addListener(() {
      logger.log('$runtimeType / init / Push was disabled by user.');
    });

    connector.requestNotificationPermissions();
  }

  @override
  void initState() {
    
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Plugin example app'),
        ),
        body: Text("Test"),
      ),
    );
  }

  Future<dynamic> onPush(Map<String, dynamic> data) {
    logger.log('onPush: $data');
    return Future.value();
  }

  Future<dynamic> onBackgroundPush(Map<String, dynamic> data) async {
    logger.log('onBackgroundPush: $data');
    return Future.value();
  }
}
`

Flutter Doctor: 

`[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-AE)
    • Flutter version 1.12.13+hotfix.8 at /Users/admin/Documents/flutter
    • Framework revision 0b8abb4724 (4 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • XXXXXX  iPhone • 9fdeba462082810d9269b60807016bb7a56bf2e7 • ios • iOS 10.3.3`

Result after running is no result on log whatsoever.

**Comment by aatmmr** [comment]
If I see correctly, you are not calling the `init()` method. Try calling it in the `initState()` method before you call `super.initState()`.

**Comment by rufw91** [comment]
Oh yes i have called the in iniState still no luck. Are you able to reproduce? 

> If I see correctly, you are not calling the `init()` method. Try calling it in the `initState()` method before you call `super.initState()`.

**Comment by aatmmr** [comment]
I tried your code and used the code I put into [this gist](https://gist.github.com/aatmmr/ed894bad04550aad624955c8e330a4b0).

Make sure you open the iOS project under `ios/Runner.xcworkspace` with Xcode and add the following capabilities:

![Screenshot 2020-02-15 at 21 20 12](https://user-images.githubusercontent.com/15815012/74594643-fb233280-5038-11ea-9fcb-927bd0cbaa23.png)

I tested the code on a iPhone 6 with iOS 12.4.5 and it shows the device token. It however, doesn't seem to work on iOS 13.*

**Comment by szotp** [comment]
@rufw91 please check my updated readme: https://github.com/mwaylabs/flutter-apns#troubleshooting

And paste the printer error.

@aatmmr thanks for support

**Comment by rufw91** [comment]
Thanks, turn out my older 5c had issues I tested on iPhone 8 no issues at all thanks for support.

**Comment by aatmmr** [comment]
I’m always happy to help. Thanks for the troubleshooting hints @szotp.
