### ISSUE TITLE
Unable to get firebase token on Android

### ISSUE THREAD

**Issue by phamotcreations** [mwaylabs/flutter-apns#18]
`connector.token.addListener((){
print('Token ${connector.token.value});
});`

Returns nothing
Using flutter_apns: ^1.1.0
Pubspec.lock has firebase_messaging: 6.0.13

**Comment by szotp** [comment]
Can you check on latest master? I upgraded to 6.0.16.

**Comment by szotp** [comment]
Clasing after lack of response.
