### ISSUE TITLE
The Apns Token get by listening the connector.token is it the same that FCM.getToken method return ?

### ISSUE THREAD

**Issue by Yirmerah** [mwaylabs/flutter-apns#20]
Hi,

I just wanted to know if The Apns Token get by listening the connector.token is the same that Fcm.getToken method return ?
Because right know i'm using FCM, it works fine for Android but when it comes to IOS, i get messaging/registration-token-not-registered Error by FCM console when trying to send a notification.
So what i'm trying to do is to use directly the native ways of Apple to see if it can work.
Do i also have to change _firebaseMessaging.configure() with     connector.configure() or i can keep my firebaseMessaging.configure even with IOS ?

**Comment by szotp** [comment]
This plugin is only for people who don't want to use firebase on iOS. It disables it and allows you to use APNS tokens. These tokens are of course different from firebase tokens, and you send pushes by communicating with apple.
