### ISSUE TITLE
connector.token not working 

### ISSUE THREAD

**Issue by Yirmerah** [mwaylabs/flutter-apns#21]
I don't understand why, but it looks like i can't get the Apns Token from the connector.token.
Every time i  tried this on a IOS simulator it print nothing .
And even if i tried it on a real IOS device, it's still not working.

```
  @override
  void initState() {
    super.initState();

  getIOSPermission() {
    _firebaseMessaging.requestNotificationPermissions(
        IosNotificationSettings(alert: true, badge: true, sound: true));
    _firebaseMessaging.onIosSettingsRegistered.listen((settings) {
      print("Settings registered:$settings");
    });
  }
    if (Platform.isIOS) {
      getIOSPermission();
      connector.requestNotificationPermissions();
    }



     connector.token.addListener(() {
            print('Apns Token ${connector.token.value}');
            usersRef.document(firebaseUser.uid).updateData(
                {"IOsToken": connector.token.value});
      })

_firebaseMessaging.configure(
      onLaunch: onPush,
      onResume: onPush,
      onMessage: onPush,
      onBackgroundMessage: onBackgroundPush,
    );
 }
```
ive enable all (enable Push Notifications and Background Modes, and enable Background fetch and Remote notifications under Background Modes.) and followed all the firebase messaging instruction and APNS IOs configure steps.
I'm not using  connector .config method, is it a problem ?
Any help would be nice,

**Comment by szotp** [comment]
Hi, can you tell me if using this library directly from master fixes your problem? If yes, I will release a new version.

**Comment by Yirmerah** [comment]
Still not working, i can't even catch token with getToken From FirebaseMessaging when adding your library

**Comment by Yirmerah** [comment]
Btw i use the flutter local notification plugins can it be a problem ?
I also disable the method swizzling .

**Comment by szotp** [comment]
No, it should be working in current master.

Did you add this?
```
if #available(iOS 10.0, *) {
  UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}
```

**Comment by Yirmerah** [comment]
Yes i did.

Here my **AppDelegate.swift** :

```
import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    }
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

}
```
Here how i get the **current master  and import it**, maybe i failed here : 
 ```
 flutter_apns:
    git:
      url: git://github.com/mwaylabs/flutter-apns.git
      ref: master

import 'package:flutter_apns/apns.dart';
```

Here how i try to get the Apns Token for IOS:

```
Platform.isAndroid
        ? _firebaseMessaging.getToken().then((token) {
            print("Firebase Messaging Token: $token\n");
            usersRef
                .document(firebaseUser.uid)
                .updateData({"androidNotificationToken": token});
          })
        : connector.token.addListener(() {
            print('Apns Token ${connector.token.value}');
            usersRef.document(firebaseUser.uid).updateData(
                {"androidNotificationToken": connector.token.value});
          });

    //I also add this just to see if the APNS token is the same as the firebaseMessaging Token
    _firebaseMessaging.getToken().then((token) {
      print("Firebase Messaging Token: $token\n");
      usersRef.document(firebaseUser.uid).updateData({"FCMToken": token});
    });
```

Here how i get the user permission :   

```
  getIOSPermission() {
    _firebaseMessaging.requestNotificationPermissions(
        IosNotificationSettings(alert: true, badge: true, sound: true));
    _firebaseMessaging.onIosSettingsRegistered.listen((settings) {
      print("Settings registered:$settings");
    });
  }


void requestIOSPermissions() {
    flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            IOSFlutterLocalNotificationsPlugin>()
        ?.requestPermissions(
          alert: true,
          badge: true,
          sound: true,
        );
  }
     if (Platform.isIOS) {
      getIOSPermission();
      requestIOSPermissions();
      connector.requestNotificationPermissions();
    }
```

Btw when i'm running it on the simulator just to see the log here what error i see : 

Unhandled Exception: MissingPluginException(No implementation found for method getToken on channel plugins.flutter.io/firebase_messaging), he is pointing the 2nde getToken (Because it's the only getToken called where i didn't add a platform conditions)

I also get this : 
Unhandled Exception: MissingPluginException(No implementation found for method configure on channel plugins.flutter.io/firebase_messaging)
which is pointing the 
_firebaseMessaging.configure(
      onLaunch: onPush,
      onResume: onPush,
      onMessage: onPush,
      onBackgroundMessage: onBackgroundPush,
    );

And this : 

Unhandled Exception: MissingPluginException(No implementation found for method requestNotificationPermission on channel plugins.flutter.io/firebase_messaging)

**Comment by Yirmerah** [comment]
@szotp  ??

**Comment by szotp** [comment]
This plugin disables firebase on iOS so you should not be using itt. Perhaps your calls to _firebaseMessaging are crashing and connector.requestNotificationPermissions is never reached.
