### ISSUE TITLE
Is it possible to use this without method swizzling?

### ISSUE THREAD

**Issue by Ben-Baert** [mwaylabs/flutter-apns#22]
I haven't found this in the docs. 

Is it possible to use this without method swizzling? I have some relevant methods that are already overridden so this would be the only way to make this work.

**Comment by szotp** [comment]
Swizzling is only used to disable firebase, by replacing registerWithRegistrar method with empty implementation. 
Otherwise you would have two libraries doing the same thing and breaking stuff.

Are you saying that you are already swizzling this method?

**Comment by Ben-Baert** [comment]
Well I actually need to include Firebase Auth which requires a token, hence why a custom implementation is probably required. 

Isn't it possible to send this token both to Firebase for their authentication purposes and have this work?

**Comment by szotp** [comment]
Firebase Auth requires push token? Strange.

If that's the case then you should just use firebase for pushes. If that's not option for some reason, then you could also override `didRegisterForRemoteNotificationsWithDeviceToken` method and send this token to yourself through method channel.

**Comment by amanokerim** [comment]
@szotp 

> Firebase Auth requires push token? Strange.
>
>If that's the case then you should just use firebase for pushes. If that's not option for some reason, then you could also > override didRegisterForRemoteNotificationsWithDeviceToken method and send this token to yourself through method > channel.
I am not familiar with native iOS development, where can I find example? How can I use pure APNS with Firebase auth in one project?
