### ISSUE TITLE
Questions about the plugin

### ISSUE THREAD

**Issue by Yirmerah** [mwaylabs/flutter-apns#23]
Can I handle notification on background with this plugin for IOS ?
I know that using fcm I can't but can I with flutter APNs ?
I also wanted know if there is the same issue with  auto cleaning notifications when entering foreground (iOS) using this plugin.
https://github.com/MaikuB/flutter_local_notifications/issues/134
https://github.com/MaikuB/flutter_local_notifications/issues/641
This issue seem to be link to fcm but since here it's not fcm could it solve the issue ?

**Comment by szotp** [comment]
Yes, there is nothing special about background notifications in iOS. You will have to configure your iOS project correctly.

The autocleaning you mentioned is currently enabled. If you need this, I could add a setting to disable it.

**Comment by mrdc** [comment]
> The autocleaning you mentioned is currently enabled. If you need this, I could add a setting to disable it.

@szotp Yes, please, add a setting - I've checked plugin's code and haven't found a place where it can be changed.
