### ISSUE TITLE
Allow for push notification in foreground (Improvement)

### ISSUE THREAD

**Issue by FloPMT** [mwaylabs/flutter-apns#24]
Hey guys, first of all thank you so much for this repo, it helped my company a lot! I did have one issue that I resolved for iOS: push notifications weren't showing when the app was in foreground and there was no configuration option for it built into this plugin. Please take a look at my changes (two commits) here and it'd be fantastic to see this as an option moving forward:
https://github.com/FloPMT/flutter-apns/commits/master

**Comment by szotp** [comment]
Hi, we can add this but it should be configurable somehow so people can dacide if they want to show native notification or display something as currently.

If you could implement this, then please do and send PR, if not, I will do it when I have time.

**Comment by FloPMT** [comment]
@szotp I agree! Unfortunately I don't have time at the moment and no experience building native extensions either.. If that changes I'll create a PR, thanks!

**Comment by andzejsw** [comment]
Wow. I actually need this one too in my project. Great idea!

**Comment by szotp** [comment]
Added on master. I will test it after the weekend and release new version.

**Comment by lordgreg** [comment]
The enhancement was release with version [1.4](https://github.com/mwaylabs/flutter-apns/tree/1.4.0).
