### ISSUE TITLE
Update version of the firebase messaging dependency to 7.0.0

### ISSUE THREAD

**Issue by devjeff** [mwaylabs/flutter-apns#28]
The firebase messaging plugin was updated in version 7.0.0 to use firebase_core features. It would be nice if the apns plugin would allow to use the updated version of firebase messaging. As there were no breaking changes, this shouldn't make any problems.

Currently a dependency resolution error is displayed when one tries to change the firebase messaging version to 7.0.0.

**Comment by szotp** [comment]
Hi, sorry for the delay. Package was updated.

**Comment by devjeff** [comment]
Thanks)
