### ISSUE TITLE
Notification handlers never called

### ISSUE THREAD

**Issue by frankvollebregt** [mwaylabs/flutter-apns#29]
First off: Thank you for this plugin!

I am trying to use notifications on iOS and Android (via APNs and FCM), which I publish from Amazon AWS. When the app is running in the background (or is terminated), the notification pops in, which opens the app when I tap it. However, on iOS, none of the callback functions are ever called.

In the `initState` function of my main widget, I initialize the `PushConnector` as `_messaging`. I then try to set the callback handlers, which does not work (on iOS).
```
_messaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
        // further process message content
      },
      onBackgroundMessage: myBackgroundMessageHandler,
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
        // further process message content
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");
        // further process message content
      },
    );
```
EDIT: `myBackgroundMessageHandler` also does the same print, but the output is never shown either.

If anyone has any clue what could be causing this behaviour, I would be very grateful.

**Comment by frankvollebregt** [comment]
I managed to resolve this by now. Apparently, I needed to pass the `click_action` to `"FLUTTER_NOTIFICATION_CLICK"` not just for Android (as documented in FB messaging), but also for iOS. After this, the callback was called as expected.

**Comment by andzejsw** [comment]
> I managed to resolve this by now. Apparently, I needed to add the `click_action` and set it to `"FLUTTER_NOTIFICATION_CLICK"` not just for Android (as documented in FB messaging), but also for iOS. After this, the callback was called as expected.

Hi. Can you give some example? I have same problem, but don't know how to fix it.

**Comment by frankvollebregt** [comment]
I'll do so tomorrow!

**Comment by frankvollebregt** [comment]
> 
> 
> > I managed to resolve this by now. Apparently, I needed to add the `click_action` and set it to `"FLUTTER_NOTIFICATION_CLICK"` not just for Android (as documented in FB messaging), but also for iOS. After this, the callback was called as expected.
> 
> Hi. Can you give some example? I have same problem, but don't know how to fix it.

For an iOS message, you can use a body like this:
```
{
  "aps":
  {
    "alert": "Hello iPhone!"
  },
  "data":
  {
    "click_action": "FLUTTER_NOTIFICATION_CLICK",
    "id": "1",
    "message": "Hello iPhone in data",
    "status": "done"
  }
}
```

When published with the `click_action` in the `data` part, the messages did arrive for me.

**Comment by andzejsw** [comment]
> > > I managed to resolve this by now. Apparently, I needed to add the `click_action` and set it to `"FLUTTER_NOTIFICATION_CLICK"` not just for Android (as documented in FB messaging), but also for iOS. After this, the callback was called as expected.
> > 
> > 
> > Hi. Can you give some example? I have same problem, but don't know how to fix it.
> 
> @andzejsw For an iOS message, you can use a body like this:
> 
> ```
> {
>   "aps":
>   {
>     "alert": "Hello iPhone!"
>   },
>   "data":
>   {
>     "click_action": "FLUTTER_NOTIFICATION_CLICK",
>     "id": "1",
>     "message": "Hello iPhone in data",
>     "status": "done"
>   }
> }
> ```
> 
> When published with the `click_action` in the `data` part, the messages did arrive for me.

Thank you a lot!
