### ISSUE TITLE
[firebase_messaging] No messages in background. + [flutter_apns] No Token.

### ISSUE THREAD

**Issue by Klingens13** [mwaylabs/flutter-apns#3]
Hi, could anyone tell me please how to get firebase working on ios? I got firebase messaging etc. installed, but messages are only going through in simulators and if the app is in foreground. I tried getting it to work with flutter_apns but there I'm stuck at getting the token. But there it's only returning  `flutter: ValueNotifier<String># **some random value** (null)`. Does anyone know how to at least get the token and from then on, maybe get everything to work?
Thanks

**Comment by szotp** [comment]
Hi @Klingens13 if you are interested in running firebase_messaging on iOS then this plugin is not for you. Please ask your question on stackoverflow or https://github.com/flutter/flutter/labels/p%3A%20firebase_messaging.
