### ISSUE TITLE
Duplicate event on IOS

### ISSUE THREAD

**Issue by cuong292** [mwaylabs/flutter-apns#31]
It's look like the onResume and onLaunch is duplicate on IOS. it trigger both when app is terminated.
APNS version : latest
IOS Version : 13.5.1

-Flutter doctor 

`[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E258a, locale en-US)
    • Flutter version 1.20.4 at /Applications/AndroidProject/flutter
    • Framework revision fba99f6cf9 (3 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/apple/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/apple/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 4.1 Preview.app/Contents
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
`

**Comment by szotp** [comment]
Can confirm, will fix.

**Comment by szotp** [comment]
Fixed in 1.4.1

**Comment by MobiliteDev** [comment]
Same problem here. onResume is called twice. Firtst time with no UNNotificationAction.getIdentifier and second time with it.

**Comment by stringeecom** [comment]
Sample problem here. Any update on this??
Version 1.5.1
