### ISSUE TITLE
README.md for iOS is probably wrong

### ISSUE THREAD

**Issue by HironobuIga** [mwaylabs/flutter-apns#33]
I added code below to AppDelegate.swift following README.md.

```swift
UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
```
Then I found that connector.configure(~) method didn't be called.
When I deleted it from AppDelegate.swift, connector.configure was called.

So I think there may be mistake in README.md.

**Comment by szotp** [comment]
Strange, but this method is required. And firebase_messaging also mentions it: https://pub.dev/packages/firebase_messaging

If you delete this line then app should actually fail with assertionFailure.

If I'm wrong then please provide some sample code.

**Comment by HironobuIga** [comment]
Thank you for your check.Yes, I think it's strange...I will try to make minimum sample of this issue, pls wait a while.

**Comment by szotp** [comment]
Please reopen if you have more details, AFAIK that line is necessary.
