### ISSUE TITLE
No background messages received on iOS background

### ISSUE THREAD

**Issue by andzejsw** [mwaylabs/flutter-apns#35]
On iOS app Foreground apns messages are received. But when I close app, they are not. Everything's works great again, after I open app. Is it some bug or I am just missing something?

**Comment by andzejsw** [comment]
I have enabled "Background fetch" and "Remote notifications" background modes in capabilities, but still not working.

**Comment by szotp** [comment]
Hi, what's the payload? Is this regular or silent push?

**Comment by andzejsw** [comment]
> Hi, what's the payload? Is this regular or silent push?

`{'aps': {'event': 'myEventUri', 'payload': {'callID': 111, 'lastStateChange': 1604480748, 'caller': 'xxx', 'destination': 'xxx', 'state': 4, 'started': 1604480746.726724,}}, 'content-available': 1}`
And it is silent push

**Comment by andzejsw** [comment]
Issue was on my side. Wrong data handling.

**Comment by prafulkadam007** [comment]
I am also facing the same issue  with below dummy payload I am getting event when app is in foreground but nothing works when it's in background mode.
{
	"aps":{
		"alert":"Test",
		"sound":"default",
		"badge":1
	}
}
