### ISSUE TITLE
Add support of firebase_messaging version 8.0.0-dev

### ISSUE THREAD

**Issue by TatankaConCube** [mwaylabs/flutter-apns#36]
[New version](https://pub.dev/packages/firebase_messaging/versions/8.0.0-dev.5)  contains a lot of improvements and fixes, please add its support in separated branch or release.

**Comment by aytunch** [comment]
how can we get apns token while using firebase messaging? I can not send a valid apns token to connectyube

**Comment by TatankaConCube** [comment]
not actual request, closing, now we can use pure firebase_messaging without third-party libs

**Comment by szotp** [comment]
@aytunch you can override `didRegisterForRemoteNotificationsWithDeviceToken` in your AppDelegate (don't forget to call super), no need to use flutter_apns at all.

**Comment by szotp** [comment]
@TatankaConCube If you needed flutter_apns after all, you could dependency override: 
```
dependency_overrides:
  firebase_messaging: ^8.0.0-dev
```
it should work if there are no breaking changes

**Comment by iberatkaya** [comment]
@szotp There seems to [small breaking changes](https://firebase.flutter.dev/docs/migration#messaging) with `firebase_messaging: ^8.0.0-dev.11`. Do you plan to upgrade the plugin's `firebase_messaging` version? Also, have you considered to make a standalone version of this plugin without `firebase_messaging`?

**Comment by HugoHeneault** [comment]
@iberatkaya I made a standalone version including *only* iOS notifications here: 

https://github.com/OwnWeb/flutter-apns/tree/feat/without-firebase

@szotp Is it worth mentioning it on your README? Should I create another plugin based on your work? 🤔
