### ISSUE TITLE
connector.token.addListener never call

### ISSUE THREAD

**Issue by bratlove123** [mwaylabs/flutter-apns#38]
I'm using Flutter beta: v1.24.0-10.2.pre. Seems like addListener never call and never get token. I already add the log error in AppDelegate.swift but still not get any error from console log application. Note that I'm testing on real device.

**Comment by szotp** [comment]
Just tested the example app on Flutter 1.24.0-10.2.pre, works fine.

Can you run it yourself (you will need to change bundle id and provisioning to your own) and see what happens?

**Comment by bratlove123** [comment]
Hi @szotp ,
I created a new project and its works. May be my one conflict with One Signal. Thanks for your quick response. I close now.
