### ISSUE TITLE
firebase background messages handling missing

### ISSUE THREAD

**Issue by d-silveira** [mwaylabs/flutter-apns#4]
Hi, 

Thanks for your work!
I'd like to report that you're missing background message handling for firebase.
Can you please add it, or at least add support for only handling apns, letting users configure firebase directly through firebase-messaging?

Thanks again,
Regards

**Comment by szotp** [comment]
I will look into it.

**Comment by szotp** [comment]
I added this, but on stable channel it crashes:
https://github.com/FirebaseExtended/flutterfire/issues/144

It' doesn't crash on master channel though.

**Comment by iapicca** [comment]
https://github.com/FirebaseExtended/flutterfire/issues/125

**Comment by broberts-nybble** [comment]
so is it fixed or still broken?

**Comment by digarahayu** [comment]
In flutter Channel stabil 1.9.x onMessage working, but onResume and onLauch not working on iOS13 
I saw a person use flutter Channel every thing work well . Maybe you just need wait for new stable version. A already try to find a way for Couple day but still not working hahahah

**Comment by szotp** [comment]
@broberts-nybble it's fixed in this plugin, but this feature seemed buggy in firebase_messaging, so it may not work properly.
