### ISSUE TITLE
onLaunch does not work on iOS.

### ISSUE THREAD

**Issue by CalvinZhan-NKUST** [mwaylabs/flutter-apns#42]
When I swipe up app. I click the notification, but app doesn't wake up. It just like crash. I ran the example code.

**Comment by szotp** [comment]
It's not possible to test this case in debug mode because in that situation Flutter does not work without debugger attached.

The crash is actually a bug in flutter, I have added more detailed description here https://github.com/flutter/flutter/issues/67624#issuecomment-801971172
