### ISSUE TITLE
iOS still installing Firebase pods, expected?

### ISSUE THREAD

**Issue by danielnordh** [mwaylabs/flutter-apns#45]
I was not expecting flutter-apns to require Firebase pods on iOS, since it is only using it for Android.
Is this the expected behavior or might I be doing something wrong?
Would love not to include them.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/3393669/109045368-63383a00-76cb-11eb-8552-f4f900c9f8d9.png">

**Comment by szotp** [comment]
Sadly, that's expected behavior. That's because we need firebase_messaging for the android side, and I did not figure out yet how to exclude it from pods.
