### ISSUE TITLE
Support mutable-content flag in APNS notifications to change displayed notification content

### ISSUE THREAD

**Issue by devjeff** [mwaylabs/flutter-apns#47]
This is a feature request. I would like to be able to change the displayed content of a push notification as mentioned in this article:

https://developer.apple.com/documentation/usernotifications/modifying_content_in_newly_delivered_notifications

This becomes necessary if you receive encrypted messages or if the message only contains a technical message id and the client needs to load the actual message content in a subsequent step. It would be great if one could register a Flutter callback function (similar to onbackgroundMessage from firebase_messaging) that is called when a push notification is received. The function would return the content that should be displayed in the notification instead of the original data in the notification dictionary.

**Comment by lordgreg** [comment]
Thank you for your info devjeff. We'll try to add this possibility to the plugin for the next major release.

**Comment by devjeff** [comment]
Awesome, thanks

**Comment by krillefear** [comment]
Sorry that I need to ask, but does this mean that this is now implemented? The issue has been closed without referring a pull request. Can this feature be used by just using the `onBackgroundMessage` handler? For me it is not that clear as the onBackgroundMessage function type has the return type Future<void>
