### ISSUE TITLE
No push notifications when an app is  in foreground and no callbacks onMessage

### ISSUE THREAD

**Issue by mrdc** [mwaylabs/flutter-apns#49]
Hello,

I'm having the issue with push notifications: no notifications when my app is in foreground (also no callbacks `onMessage`).
Also `onPush` is never called, but my app receives push notifications when it's in background.

I'm using flutter_apns: 1.4.1, Flutter 2.0.0

Here is the code I use (it's 99% from the example):
```dart

void main() {
...
  WidgetsFlutterBinding.ensureInitialized();
...
}

Future<void> initPush() async {
    final connector = createPushConnector();
    if (connector is ApnsPushConnector) {
      connector.shouldPresent = (x) => Future.value(true);
    }
    connector.configure(
      onLaunch: (data) => onPush('onLaunch', data),
      onResume: (data) => onPush('onResume', data),
      onMessage: (data) => onPush('onMessage', data),
      onBackgroundMessage: _onBackgroundMessage,
    );
    connector.token.addListener(() async {
      print('${connector.token.value}');
     
    });
    connector.requestNotificationPermissions();
}


  Future<dynamic> onPush(String name, Map<String, dynamic> payload) {

    print('$payload');
    final action = UNNotificationAction.getIdentifier(payload);

    if (action == 'MEETING_INVITATION') {
      print('MEETING_INVITATION');
    }

    return Future.value(true);
  }

  Future<dynamic> _onBackgroundMessage(Map<String, dynamic> data) =>
      onPush('onBackgroundMessage', data);

```

Any ideas what can be wrong?

**Comment by szotp** [comment]
Hi have you seen [Troubleshooting section](https://github.com/mwaylabs/flutter-apns#troubleshooting)?

**Comment by mrdc** [comment]
> Hi have you seen [Troubleshooting section](https://github.com/mwaylabs/flutter-apns#troubleshooting)?

Hi! Yes, no errors. Background pushes are delivered and I see them without issues, so push notifications actually work, but not in foreground and no onMessage callbacks, so I can't process a data which comes from backend :(

Maybe for foreground the issue is here?
`if (connector is ApnsPushConnector) {
      connector.shouldPresent = (x) => Future.value(true);
    }`

**Comment by mrdc** [comment]
> Do you have `UNUserNotificationCenter.current().delegate = self` added? If it was missing, I would expect the behavior your are describing. I'll add assertion in code for this.

Yes, 
`if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
    }`

I've also checked with flutter_local_notifications plugin and foreground notifications (triggered by the mob app) are working.

**Comment by mrdc** [comment]
@szotp 

When I click on push notification (when my mob app is in background) in logs I see this:
`Warning: UNUserNotificationCenter delegate received call to -userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: but the completion handler was never called.`

**Comment by mrdc** [comment]
@szotp It works with the latest update: 1.5.0 :)

Still need to figure out how to get data from push notifications, but at least when I click on notification it shows something in logs.
