### ISSUE TITLE
do you support receiving messages in IOS both from firebase and apns?

### ISSUE THREAD

**Issue by d-silveira** [mwaylabs/flutter-apns#5]
Hi

do you support receiving messages in IOS both from firebase and apns?

Regards,

**Comment by szotp** [comment]
Hi @d-silveira 

You could try installing regular firebase plugin without flutter-apns, and then overwriting this method:

https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622958-application

in your AppDelegate. If you call super, firebase will register itself, but you may also send this token to your own backend and send pushes with it. It's a bit of a hack, but it worked fine last time I tried.

**Comment by szotp** [comment]
I hope that I answered your question.
