### ISSUE TITLE
Example can't compile

### ISSUE THREAD

**Issue by MobiliteDev** [mwaylabs/flutter-apns#57]
I have issues running your example with Flutter 2.2.0.

![image](https://user-images.githubusercontent.com/54275508/119119677-b51f0080-ba2b-11eb-8a72-44d6a42f98cb.png)

Apparently the quickest way to fix this is to change firebase_messaging from ^9.0.0 to ^10.0.0 and firebase_core: ^1.2.0.

**Comment by Menelphor** [comment]
Having the same issue, with my App right now. 

Just gonna comment here to get notified, if the issue gets resolved :D

**Comment by danielRi** [comment]
politely bumping this issue.

**Comment by Menelphor** [comment]
https://github.com/mwaylabs/flutter-apns/pull/58
