### ISSUE TITLE
Notifications dissapear from the notification center when the app becomes active

### ISSUE THREAD

**Issue by gerardomedina** [mwaylabs/flutter-apns#59]
This happens because the applicationIconBadgeNumber is set to 0 in the method applicationDidBecomeActive from the file FlutterApnsPlugin.swift

![image](https://user-images.githubusercontent.com/3533355/120227157-45202f80-c20e-11eb-81fd-78ba2d5fb307.png)

Can this code be removed or validated (with a flag) so notifications remain in the notification center until the user taps them?

Thanks in advance!

**Comment by BayeNN** [comment]
Hi all @danielkono, I'm having the same https://github.com/mwaylabs/flutter-apns/issues/59 issue.
Will really appreciate if the above fix could be made or any updates / recommendations on this from you...
Thanks!

**Comment by christofkost** [comment]
Hey everybody! We created a pull request to fix this issue. So this problem will be solved on the next flutter_apns-release. This will probably happen this week.
Best regards!
