### ISSUE TITLE
flutter_apns ^1.5.0-dev.1 which depends on firebase_messaging ^9.0.0, firebase_messaging ^9.0.0 is required.

### ISSUE THREAD

**Issue by DineshKachhot** [mwaylabs/flutter-apns#60]
I am getting error of using firebase_messaging ^9.0.0, while in my project I am using firebase_messaging ^10.0.0, I seen the directory, seems line flutter_apns using firebase_messaging ^10.0.0, please help.

**Comment by dmytrobogovych** [comment]
The same situation...

**Comment by alimovshohrukh** [comment]
Same problem. But, until they merge the latest pull, here is a quick solution:

```
dependency_overrides:
  firebase_messaging: ^10.0.1
```

**Comment by Nealsoni00** [comment]
Are there any conflicts that arise if you force ^10.0.1?

**Comment by DineshKachhot** [comment]
This issue is fixed with latest version of firebase messaging, firebase_messaging: ^10.0.4, so no need to override dependency now.

**Comment by ben-xD** [comment]
@DineshKachhot you could close the issue if you think it's not a problem anymore.
