### ISSUE TITLE
How to use this plugin for silent notifications for iOS?

### ISSUE THREAD

**Issue by jack24254029** [mwaylabs/flutter-apns#61]
Can the plugin use for silent notifications on iOS?

**Comment by jack24254029** [comment]
I set the `content-available` is `1` in `apns` json object and it is work when the app is inactive state, but it is not work when the app is terminated or suspended state.

**Comment by ben-xD** [comment]
Although `PushConnector#configure` takes a `onBackgroundMessage`, this is currently not implemented in anyway. You'd have to look at [flutter_apns_only](https://pub.dev/packages/flutter_apns_only) package which is also in this repo:

https://github.com/mwaylabs/flutter-apns/blob/master/flutter_apns_only/lib/flutter_apns_only.dart#L46-L57

**Comment by christofkost** [comment]
There is no functionality for background push notifications (a.k.a. silent notifications), yet. 
Pull requests are always welcome since the original developer is not active on this package anymore.
