### ISSUE TITLE
How to use flutter-apns along with firebase-messaging?

### ISSUE THREAD

**Issue by thothai94** [mwaylabs/flutter-apns#63]
I would like to use both flutter-apns and firebase-messaging to receive and handle push notification. But when I receive APNs device token by flutter-apns, firebase-messaging can not and do not receive any notification.
Please tell me, how to use both of them?
Thank you so much!

**Comment by christofkost** [comment]
Do you want to utilize firebase-messaging on iOS or Android? On iOS, utilizing both is currently not possible.
