### ISSUE TITLE
Request: getAuthorizationStatus and requestNotificationPermissions should return futures

### ISSUE THREAD

**Issue by fbcouch** [mwaylabs/flutter-apns#64]
It would be nice to be able to wait for `getAuthorizationStatus` and/or `requestNotificationPermissions` to return. Those methods could wait to call `result` on the native side until the user takes action or the notification settings are returned, respectively. Something like changing this:
```
void getAuthorizationStatus() {
  _channel.invokeMethod('getAuthorizationStatus', []);
}
```

to something along the lines of this:

```
Future<String> getAuthorizationStatus() async {
  return  _channel.invokeMethod('getAuthorizationStatus', []);
}
```

**Comment by christofkost** [comment]
Thanks for the PR we will review it!
