### ISSUE TITLE
Getting Token

### ISSUE THREAD

**Issue by cristoferdomingues** [mwaylabs/flutter-apns#7]
First of all, thank you very much for your service!

I'm trying to get the device token running through Xcode Iphone Simulator, but I'm not being able of getting the device token.
- Is it possible get the token when running through the simulator?
If so, should not print the token when: 
`  connector.token.addListener(() {
      print('Token ${connector.token.value}');
    });
    connector.requestNotificationPermissions();`

Thanks!

**Comment by szotp** [comment]
Sorry, not possible. iOS simulator does not support push notifications.

**Comment by GioPan04** [comment]
@cristoferdomingues now with xcode 11.4 you can recive notification within the simulator
