### ISSUE TITLE
Customizing Notification

### ISSUE THREAD

**Issue by Maz47** [mwaylabs/flutter-apns#70]
I am currently developing an App which works with a backend which sends flutter_apns notifications. I implemented this plugin for displaying the notifications. Unfortunatelly I can't customize the data sent from the backend, but is there any possibility to customize the notification on the client and display it. If not is there a way to disable displaying the default notification from flutter_apns and instead handle it myselfe with flutter_local_notifications?

**Comment by christofkost** [comment]
Hey @Maz47 
We would need some more informations. How are you sending the push notifications?
This CURL shows how a request to APNS in debug mode should look like:
`curl -v \
-d '{"aps":{"alert":"<message>","badge":42}}' \
-H "apns-topic: <bundle id>" \
-H "apns-priority: 10" \
--http2 \
--cert <certificate file> \
https://api.development.push.apple.com/3/device/<device token>`
