### ISSUE TITLE
Can not get result of notification permission prompt on iOS

### ISSUE THREAD

**Issue by NickCullen** [mwaylabs/flutter-apns#73]
Hey,

Is this package still active? 

Currently, on iOS there is no way for us to determine the result of the user pressing yes/no on the prompt for requesting notification permissions.

There seems to be a [PR outstanding](https://github.com/mwaylabs/flutter-apns/pull/65) that would fix this issue. Using futures for this kind of logic seems better practice.

```
flutter-apns 1.5.1
flutter 2.5.2
iPhone 12 pro max (physical device)
iOS 14.4.1
```

Here is an example of what we're trying...

`onIosSettingsRegistered ` stream seems to be totally unused by the package. The only reference to it internally is calling dispose. 

`token` and `isDisabledByUser` value listeners never get called

We also tried listening for `authorizationStatus`, but still the same result.

I would expect the relevant value notifier to call its listeners after the user has interacted with the notification prompt? 

```
  Future<bool> requestPermission() async {
    assert(_connector.authorizationStatus.value != null);

    final completer = Completer<bool>();

    void onAuthorizationStatus() {
      completer.complete(_connector.authorizationStatus.value == 'authorized');
      _connector.authorizationStatus.removeListener(onAuthorizationStatus);
    }

    void onSettingsRegistered(IosNotificationSettings _) {
      _connector.authorizationStatus.addListener(onAuthorizationStatus);
      _connector.getAuthorizationStatus();
    }

    void onDisabled() {
      _connector.isDisabledByUser.removeListener(onDisabled);

      _connector.authorizationStatus.addListener(onAuthorizationStatus);
      _connector.getAuthorizationStatus();
    }

    void onToken() {
      _connector.token.removeListener(onDisabled);

      _connector.authorizationStatus.addListener(onAuthorizationStatus);
      _connector.getAuthorizationStatus();
    }

    if (_connector.authorizationStatus.value == 'notDetermined') {
      _connector.onIosSettingsRegistered.listen(onSettingsRegistered);
      _connector.isDisabledByUser.addListener(onDisabled);
      _connector.token.addListener(onToken);

      _connector.requestNotificationPermissions(
        IosNotificationSettings(
          alert: true,
          badge: true,
          sound: true,
        ),
      );
    } else {
      completer.complete(_connector.authorizationStatus.value == 'authorized');
    }

    return completer.future;
  }
```

**Comment by christofkost** [comment]
Hey @NickCullen 
Since the original developer does not maintain this package anymore, I take over the maintainer role.
I tried to identify the problem and found a solution:
`connector.requestNotificationPermissions();
 if (connector is ApnsPushConnectorOnly) {
      final authorizationStatus =
          await (connector as ApnsPushConnectorOnly).getAuthorizationStatus();
    }`

I hope this answers your question. Otherwise I will reopen this issue. Best regards!
