### ISSUE TITLE
iOS 13 token problem

### ISSUE THREAD

**Issue by bbaldwin-rezi** [mwaylabs/flutter-apns#8]
Looks like iOS 13 changed the token description field, see this discussion:

https://stackoverflow.com/questions/57839723/does-ios-13-has-new-way-of-getting-device-notification-token

Token is coming back from flutter_apns looking like this:

"{length=32,bytes=0x01a066cdf7e5aaaeb9b5fbdcd4a94987...c96abee0ef5cb5e0}"

Ellipsis is really there, so we don't even get the full token that we could parse out of that.

**Comment by szotp** [comment]
Thanks for noticing, I will push a fix soon.

**Comment by szotp** [comment]
Fixed in version 1.0.4
