### ISSUE TITLE
InvalidToken and InvalidRegistration on iOS, token valid on Android

### ISSUE THREAD

**Issue by letsgitgoin** [mwaylabs/flutter-apns#90]
More like a question unless it really is an issue. Not sure if I'm missing something but I have the application configured as per the example for iOS, I can send a test notification using Firebase console as well as using .pem cert and https://api.development.push.apple.com/3/device/myDeviceToken. I'm getting the token from PushConnector token listener.

However, when I use postman or curl along with https://fcm.googleapis.com/fcm/send, I get InvalidRegistration response. Using https://iid.googleapis.com/iid/info/myDeviceToken I get InvalidToken.

In Postman I'm using the server key for authorization and it works for Android device tokens. Am I missing something for iOS?
I've also noticed iOS token are much shorter than Android tokens, is that normal or are they both supposed to look similar?

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 11.6.3 20G415 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

EDIT: Looks like the token I'm getting while running on iOS device is the APNS token and not the FCM registration token. On adding some code in AppDelegate.swift I'm getting the firebase registration token and able to send push notification using that. **So the final question is how do I make this APNS plugin give me that FCM registration token instead of APNS device token?** I tried using FirebaseMessaging plugin directly to get FCM registration token in flutter but keep getting MissingPlugin exception for iOS, possibly because I'm trying to use FirebaseMessaging along with flutter APNS plugin.

**Comment by christofkost** [comment]
Hey @letsgitgoin 
Currently it is not possible to support iOS-FCM and APNS at the same time. But feel free to open a pull request :)

**Comment by letsgitgoin** [comment]
> Hey @letsgitgoin Currently it is not possible to support iOS-FCM and APNS at the same time. But feel free to open a pull request :)

Thanks for the response. What would be the ideal flow in this case for iOS, add native swift code to register the FCM token with our server and then use Firebase Messaging to send notifications? And the other option is using APNS directly with Apple API to send push notifications using the .pem file. Is there any other option?

**Comment by christofkost** [comment]
If you want a firebase-only solution, I would recommend using this package: https://pub.dev/packages/firebase_messaging

flutter_apns is only for retrieving push messages from Apple Push Notification Service (APNS) when Firebase should not be used for push messages in the iOS world.

**Comment by letsgitgoin** [comment]
In case this helps anyone, I ended up using the batch import API mentioned below to get FCM token using APNS token. Set sandbox to true. You will also need the server key which is available in Cloud Messaging settings.
https://developers.google.com/instance-id/reference/server#create_registration_tokens_for_apns_tokens
Test it out in postman.
