### ISSUE TITLE
reinstall there is cache

### ISSUE THREAD

**Issue by 2e2ee95304418f96** [mwaylabs/flutter-apns#95]
When I uninstall my app , and install it , but the token listener still can get token without requestNotificationPermissions.So is there  cache existed?

**Comment by christofkost** [comment]
There is no cache integrated. This issue is probably due to other circumstances.

**Comment by 2e2ee95304418f96** [comment]
I found that it need to  wait several seconds after the uninstall , and it goes to normal.
